// <auto-generated />
using System;
using ComputerInventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComputerInventory.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220513204904_ComputerInventory.Data.AppDBContext")]
    partial class ComputerInventoryDataAppDBContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComputerInventory.Models.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MachineID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GeneralRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("InstalledRoles")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MachineTypeId")
                        .HasColumnType("int")
                        .HasColumnName("MachineTypeID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("OperatingSysId")
                        .HasColumnType("int")
                        .HasColumnName("OperatingSysID");

                    b.HasKey("MachineId");

                    b.HasIndex("MachineTypeId");

                    b.HasIndex("OperatingSysId");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("ComputerInventory.Models.MachineType", b =>
                {
                    b.Property<int>("MachineTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MachineTypeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("MachineTypeId");

                    b.ToTable("MachienyType");
                });

            modelBuilder.Entity("ComputerInventory.Models.MachineWarranty", b =>
                {
                    b.Property<int>("MachineWarrantyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MachineWarrntyID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineID");

                    b.Property<string>("ServiceTag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("WarrantyExpiration")
                        .HasColumnType("date");

                    b.Property<int>("WarrantyProviderId")
                        .HasColumnType("int")
                        .HasColumnName("WarrantyProviderID");

                    b.HasKey("MachineWarrantyId");

                    b.HasIndex("WarrantyProviderId");

                    b.ToTable("MachineWarranty");
                });

            modelBuilder.Entity("ComputerInventory.Models.OperatingSys", b =>
                {
                    b.Property<int>("OperatingSysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OperatingSysID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("varchar(35)");

                    b.Property<bool>("StillSupported")
                        .HasColumnType("bit");

                    b.HasKey("OperatingSysId");

                    b.ToTable("OperatingSys");
                });

            modelBuilder.Entity("ComputerInventory.Models.SupportLog", b =>
                {
                    b.Property<int>("SupportLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupportLogID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SupportLogEntry")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("SupportLogEntryDate")
                        .HasColumnType("date");

                    b.Property<string>("SupportLogUpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SupportTicketId")
                        .HasColumnType("int")
                        .HasColumnName("SupportTicketID");

                    b.HasKey("SupportLogId");

                    b.HasIndex("SupportTicketId");

                    b.ToTable("SupportLog");
                });

            modelBuilder.Entity("ComputerInventory.Models.SupportTicket", b =>
                {
                    b.Property<int>("SupportTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupportTicketID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateReported")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateResolved")
                        .HasColumnType("date");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("IssueDetails")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineID");

                    b.Property<string>("TicketOpenedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SupportTicketId");

                    b.HasIndex("MachineId");

                    b.ToTable("SupportTicket");
                });

            modelBuilder.Entity("ComputerInventory.Models.WarrantyProvider", b =>
                {
                    b.Property<int>("WarrantyProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WarrantyProviderID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("SupportExtension")
                        .HasColumnType("int");

                    b.Property<string>("SupportNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("WarrantyProviderId");

                    b.ToTable("WarrantyPrivider");
                });

            modelBuilder.Entity("ComputerInventory.Models.Machine", b =>
                {
                    b.HasOne("ComputerInventory.Models.MachineType", "MachineType")
                        .WithMany("Machine")
                        .HasForeignKey("MachineTypeId")
                        .HasConstraintName("FK_MachineType")
                        .IsRequired();

                    b.HasOne("ComputerInventory.Models.OperatingSys", "OperatingSys")
                        .WithMany("Machine")
                        .HasForeignKey("OperatingSysId")
                        .HasConstraintName("FK_OperatingSys")
                        .IsRequired();

                    b.Navigation("MachineType");

                    b.Navigation("OperatingSys");
                });

            modelBuilder.Entity("ComputerInventory.Models.MachineWarranty", b =>
                {
                    b.HasOne("ComputerInventory.Models.WarrantyProvider", "WarrantyProvider")
                        .WithMany("MachineWarranty")
                        .HasForeignKey("WarrantyProviderId")
                        .HasConstraintName("FK_WarrantyProvider")
                        .IsRequired();

                    b.Navigation("WarrantyProvider");
                });

            modelBuilder.Entity("ComputerInventory.Models.SupportLog", b =>
                {
                    b.HasOne("ComputerInventory.Models.SupportTicket", "SupportTicket")
                        .WithMany("SupportLog")
                        .HasForeignKey("SupportTicketId")
                        .HasConstraintName("FK_SupportTicket")
                        .IsRequired();

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("ComputerInventory.Models.SupportTicket", b =>
                {
                    b.HasOne("ComputerInventory.Models.Machine", "Machine")
                        .WithMany("SupportTicket")
                        .HasForeignKey("MachineId")
                        .HasConstraintName("FK_Machine")
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("ComputerInventory.Models.Machine", b =>
                {
                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("ComputerInventory.Models.MachineType", b =>
                {
                    b.Navigation("Machine");
                });

            modelBuilder.Entity("ComputerInventory.Models.OperatingSys", b =>
                {
                    b.Navigation("Machine");
                });

            modelBuilder.Entity("ComputerInventory.Models.SupportTicket", b =>
                {
                    b.Navigation("SupportLog");
                });

            modelBuilder.Entity("ComputerInventory.Models.WarrantyProvider", b =>
                {
                    b.Navigation("MachineWarranty");
                });
#pragma warning restore 612, 618
        }
    }
}
